button1:
  number: 1
  pin: 26
button2:
  number: 2
  pin: 36
button3:
  number: 3
  pin: 8
button4:
  number: 4
  pin: 10
button5:
  number: 5
  pin: 16
button6:
  number: 6
  pin: 18
encoder1:
  number: 1
  first_pin: 22
  second_pin: 24
encoder2:
  number: 2
  first_pin: 38
  second_pin: 40